#name: CI
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 8
#        uses: actions/setup-java@v2
#        with:
#          java-version: 8
#
#      - name: Build and test
#        run: |
#          mvn test
